version: '3.8'

# Development Docker Compose Override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development Backend with Hot Reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
      - maven_cache:/root/.m2
    command: ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
    ports:
      - "8080:8080"
      - "5005:5005" # Debug port
    
  # Development Frontend with Hot Reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080/api
      - FAST_REFRESH=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - node_modules:/app/node_modules
    command: ["npm", "start"]
    stdin_open: true
    tty: true

  # Development Database with Persistent Volume
  mysql:
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./backend/src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" # Different port to avoid conflicts

volumes:
  mysql_dev_data:
    driver: local
  maven_cache:
    driver: local
  node_modules:
    driver: local
